## Main Pipeline

In [1]:
from utils.data_processor import BasicDataProcessor, LSTMDataProcessor
basic_data_processor = BasicDataProcessor(1001115026824)
basic_data_processor.prepare_basic_data()
lstm_data_processor = LSTMDataProcessor(1001115026824)
lstm_data_processor.prepare_lstm_data()

In [1]:
from main import MainPipeline, initialize_csv
from global_setting import lightcurve_list
for lightcurve in lightcurve_list[1]:
    instance = MainPipeline(lightcurve)
    instance.prepare_individual_data()
    instance.load_individual_data()
    
#     instance.run_gp()
#     instance.run_vanilla_lstm()
    y_train_std, y_cross_std = instance.run_bayesian_lstm()

Using TensorFlow backend.


5
4
1
3
2



Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/300
 - 1s - loss: 0.3032
Epoch 2/300
 - 0s - loss: 0.3028
Epoch 3/300
 - 0s - loss: 0.2646
Epoch 4/300
 - 0s - loss: 0.2511
Epoch 5/300
 - 0s - loss: 0.2340
Epoch 6/300
 - 0s - loss: 0.2166
Epoch 7/300
 - 0s - loss: 0.2039
Epoch 8/300
 - 0s - loss: 0.1849
Epoch 9/300
 - 0s - loss: 0.1813
Epoch 10/300
 - 0s - loss: 0.1527
Epoch 11/300
 - 0s - loss: 0.1410
Epoch 12/300
 - 0s - loss: 0.1321
Epoch 13/300
 - 0s - loss: 0.1234
Epoch 14/300
 - 0s - loss: 0.1240
Epoch 15/300
 - 0s - loss: 0.0983
Epoch 16/300
 - 0s - loss: 0.0871
Epoch 17/300
 - 0s - loss: 0.0708
Epoch 18/300
 - 0s - loss: 0.0744
Epoch 19/300
 - 0s - loss: 0.0699
Epoch 20/300
 - 0s - loss: 0.0753
Epoch 21/300
 - 0s - loss: 0.0565
Epoch 22/300
 - 0s - loss: 0.0560
Epoch 23/300
 - 0s - loss: 0.0493
Ep

Epoch 184/300
 - 0s - loss: 0.0195
Epoch 185/300
 - 0s - loss: 0.0186
Epoch 186/300
 - 0s - loss: 0.0224
Epoch 187/300
 - 0s - loss: 0.0174
Epoch 188/300
 - 0s - loss: 0.0192
Epoch 189/300
 - 0s - loss: 0.0165
Epoch 190/300
 - 0s - loss: 0.0156
Epoch 191/300
 - 0s - loss: 0.0214
Epoch 192/300
 - 0s - loss: 0.0165
Epoch 193/300
 - 0s - loss: 0.0172
Epoch 194/300
 - 0s - loss: 0.0175
Epoch 195/300
 - 0s - loss: 0.0252
Epoch 196/300
 - 0s - loss: 0.0208
Epoch 197/300
 - 0s - loss: 0.0181
Epoch 198/300
 - 0s - loss: 0.0257
Epoch 199/300
 - 0s - loss: 0.0190
Epoch 200/300
 - 0s - loss: 0.0247
Epoch 201/300
 - 0s - loss: 0.0212
Epoch 202/300
 - 0s - loss: 0.0204
Epoch 203/300
 - 0s - loss: 0.0199
Epoch 204/300
 - 0s - loss: 0.0181
Epoch 205/300
 - 0s - loss: 0.0161
Epoch 206/300
 - 0s - loss: 0.0187
Epoch 207/300
 - 0s - loss: 0.0167
Epoch 208/300
 - 0s - loss: 0.0157
Epoch 209/300
 - 0s - loss: 0.0191
Epoch 210/300
 - 0s - loss: 0.0207
Epoch 211/300
 - 0s - loss: 0.0190
Epoch 212/300
 - 0s 

168/168 [==============================] - 0s 10us/step


168/168 [==============================] - 0s 9us/step


168/168 [==============================] - 0s 11us/step


168/168 [==============================] - 0s 10us/step


168/168 [==============================] - 0s 10us/step


168/168 [==============================] - 0s 9us/step


48/48 [==============================] - 0s 26us/step


48/48 [==============================] - 0s 29us/step


48/48 [==============================] - 0s 31us/step


48/48 [==============================] - 0s 29us/step


48/48 [==============================] - 0s 30us/step


48/48 [==============================] - 0s 33us/step


48/48 [==============================] - 0s 31us/step


<Figure size 1200x800 with 1 Axes>

<Figure size 1200x800 with 1 Axes>

In [2]:
print(y_train_std)

[[4.8826    ]
 [4.97551   ]
 [5.133315  ]
 [5.098023  ]
 [5.289097  ]
 [5.3260555 ]
 [5.586852  ]
 [5.610163  ]
 [5.713536  ]
 [5.929701  ]
 [6.1899667 ]
 [5.951932  ]
 [6.333399  ]
 [6.109512  ]
 [6.1883173 ]
 [6.35359   ]
 [6.134386  ]
 [6.538059  ]
 [6.3955812 ]
 [6.434086  ]
 [6.2124305 ]
 [6.2164702 ]
 [5.591498  ]
 [5.748293  ]
 [5.7576365 ]
 [5.15378   ]
 [5.0027785 ]
 [4.8320494 ]
 [4.6739426 ]
 [4.351409  ]
 [4.356955  ]
 [4.0576982 ]
 [3.943824  ]
 [3.8017461 ]
 [3.564169  ]
 [3.293989  ]
 [3.0441375 ]
 [2.8359468 ]
 [2.5472207 ]
 [2.387675  ]
 [2.265123  ]
 [1.9924144 ]
 [1.7165719 ]
 [1.5786083 ]
 [1.4539862 ]
 [1.418713  ]
 [1.1540709 ]
 [0.8950049 ]
 [0.8899893 ]
 [0.68643475]
 [1.2842714 ]
 [0.8606298 ]
 [1.2414886 ]
 [0.9237035 ]
 [0.7395734 ]
 [0.61404717]
 [0.64896756]
 [0.624414  ]
 [0.6617562 ]
 [0.7876894 ]
 [0.6112906 ]
 [0.55324984]
 [0.4838323 ]
 [0.60546297]
 [0.5252642 ]
 [1.0539    ]
 [0.8914929 ]
 [1.194967  ]
 [1.3837483 ]
 [1.4733874 ]
 [1.6230214 ]
 [1.77

In [3]:
print(y_cross_std)

[[4.5147505]
 [4.7969007]
 [4.962546 ]
 [5.132976 ]
 [5.553362 ]
 [5.8655047]
 [5.6670947]
 [6.002945 ]
 [6.023219 ]
 [6.103486 ]
 [6.141882 ]
 [6.2638144]
 [6.0443726]
 [6.2282395]
 [6.1207066]
 [6.2848268]
 [6.37188  ]
 [6.184401 ]
 [6.2766676]
 [6.1096582]
 [6.008502 ]
 [6.1809196]
 [6.0733604]
 [6.119777 ]
 [5.751314 ]
 [5.831577 ]
 [5.5124836]
 [5.5294394]
 [5.451691 ]
 [5.392076 ]
 [5.4665594]
 [5.178944 ]
 [5.2007794]
 [5.057715 ]
 [4.788387 ]
 [4.6430955]
 [4.5976524]
 [4.3335176]
 [4.2364864]
 [4.2502437]
 [3.88647  ]
 [3.6349154]
 [3.390914 ]
 [3.1335454]
 [2.6326404]
 [2.3639455]
 [2.1414948]
 [1.8984911]]


In [2]:
import pickle
import numpy as np
with open('/Users/mingyu/Desktop/dataset/processed_data/basic/1001115026824.pkl', 'rb') as handle: 
    basic = pickle.load(handle)

In [3]:
np.shape(basic['t_train'])

(260,)

In [4]:
with open('/Users/mingyu/Desktop/dataset/processed_data/lstm/1001115026824_rescaled_delta_t.pkl', 'rb') as handle: 
    rescaled_delta_t = pickle.load(handle)
print(np.shape(rescaled_delta_t['scaled_delta_t_train']))

(259, 1)


In [5]:
with open('/Users/mingyu/Desktop/dataset/processed_data/lstm/1001115026824_rescaled_mag.pkl', 'rb') as handle: 
    rescaled_mag = pickle.load(handle)
print(np.shape(rescaled_mag['scaled_mag_train']))

(259, 1)


In [6]:
with open('/Users/mingyu/Desktop/dataset/processed_data/lstm/1001115026824_X_y_window_len_10.plk', 'rb') as handle: 
    X_y = pickle.load(handle)
print(np.shape(X_y['train_X']))

(249, 10, 2)


In [7]:
rescaled_mag['scaled_mag_train']

array([[0.4619883 ],
       [0.59649123],
       [0.54385965],
       [0.39181287],
       [0.42105263],
       [0.5380117 ],
       [0.1754386 ],
       [0.43859649],
       [0.49122807],
       [0.52631579],
       [0.50292398],
       [0.43274854],
       [0.45614035],
       [0.40935673],
       [0.43274854],
       [0.51461988],
       [0.37426901],
       [0.50292398],
       [0.43859649],
       [0.39181287],
       [0.43859649],
       [0.43859649],
       [0.43274854],
       [0.48538012],
       [0.5497076 ],
       [0.43274854],
       [0.57309942],
       [0.49707602],
       [0.46783626],
       [0.54385965],
       [0.38596491],
       [0.35087719],
       [0.42690058],
       [0.47953216],
       [0.43274854],
       [0.60818713],
       [0.44444444],
       [0.43859649],
       [0.36842105],
       [0.4619883 ],
       [0.46783626],
       [0.39181287],
       [0.41520468],
       [0.69005848],
       [0.52046784],
       [0.49707602],
       [0.48538012],
       [0.362

In [8]:
X_y['train_X'][0]

array([[4.61988304e-01, 1.34403151e-05],
       [5.96491228e-01, 1.33456649e-05],
       [5.43859649e-01, 1.31563647e-05],
       [3.91812865e-01, 6.13902009e-02],
       [4.21052632e-01, 2.58868040e-05],
       [5.38011696e-01, 2.56975038e-05],
       [1.75438596e-01, 2.58868040e-05],
       [4.38596491e-01, 5.19077273e-02],
       [4.91228070e-01, 2.03497728e-05],
       [5.26315789e-01, 2.02551227e-05]])

In [17]:
a = [1, 2, 3, 4, 5, 6]
a[3]

4

In [20]:
np.linspace(1, 2, 100)[:-1]

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [33]:
a = [1, 2, 3, 4, 5]
a[:-1]

[1, 2, 3, 4]

In [21]:
[1, 2, 3, 4, 5]
   [1, 1, 1, 1]
   [1, 1, 1]

[1, 1, 1]

In [28]:
X = np.arange(1).reshape(1, 1)

In [29]:
X[0, 0]

0

In [30]:
def delta_list(raw):
    delta_list = []
    for i in range(1, len(raw)):
        delta = raw[i] - raw[i - 1]
        delta_list.append(delta)
    delta_list = np.array(delta_list)

    return delta_list

In [36]:
a = np.array([1, 2]).reshape(-1, 1)

In [37]:
a

array([[1],
       [2]])

In [1]:
import numpy as np
def create_X_y(scaled_mag, scaled_delta_t, window_len):
    X, y = [], []
    for i in range(0, np.shape(scaled_mag)[0] - window_len):
        features = []
        for j in range(i, i + window_len):
            feature = np.concatenate((scaled_mag[j], scaled_delta_t[j]), axis=0)
            features.append(feature)
        X.append(features)
        y.append(scaled_mag[i + window_len])

    X = np.array(X)
    y = np.array(y)

    return X, y

In [2]:
window_len = 3
scaled_mag = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)
t = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)
scaled_delta_t = np.array([1, 1, 1, 1, 1]).reshape(-1, 1)
t_pred = t[window_len:]
X = create_X_y()

SyntaxError: invalid syntax (<ipython-input-2-2943befbc509>, line 4)

In [ ]:
def recursive(self, t_pred, X, mag_scaler):
    delta_t_pred = np.diff(t_pred)
    scaled_y_pred = []
    X_step = X[[0]]  # shape = (1, window_len, 2)
    scaled_y_pred.append(X[0, -1, 0])
    for i in range(len(delta_t_pred)):
        scaled_y_step = self.model.predict(X_step)  # shape = (1, 1)
        scaled_y_pred.append(scaled_y_step[0, 0])  # scaled_y_step[0] -> shape = (num_feature)
        if i == len(delta_t_pred) - 1:
            break

        scaled_t_step = np.expand_dims(delta_t_pred[i], axis=0)  # shape = (1, 1)
        new_feature = np.concatenate((scaled_y_step, scaled_t_step), axis=1)  # shape = (1, 2)
        X_step = np.concatenate((X_step[0][1:, :], new_feature), axis=0)  # shape = (window_len, 2)
        X_step = np.expand_dims(X_step, axis=0)  # shape = (1, window_len, 2)

    scaled_y_pred = np.array(scaled_y_pred)  # shape = (num_step, 1)
    y_pred = mag_scaler.inverse_transform(scaled_y_pred)

    return y_pred